import{a as b,i as d,S as g}from"./assets/vendor-95dc692e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();b.defaults.baseURL="https://pixabay.com/api/";const P="42552421-44c442bdd9fc0080a82eeb482";async function L(e,r,s){return await b.get(`?key=${P}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`)}const p=e=>{const r=document.querySelector(".gallery");e.length===0&&d.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"});const s=e.map(({id:t,largeImageURL:o,webformatURL:a,tags:I,likes:q,views:v,comments:$,downloads:H})=>`
      <a class="gallery__link" href="${o}">
        <div class="gallery-item" id="${t}">
          <img class="gallery-item__img" src="${a}" alt="${I}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes</b>${q}</p>
            <p class="info-item"><b>Views</b>${v}</p>
            <p class="info-item"><b>Comments</b>${$}</p>
            <p class="info-item"><b>Downloads</b>${H}</p>
          </div>
        </div>
      </a>`).join("");r.insertAdjacentHTML("beforeend",s),new g(".gallery-item",{captionsData:"alt",captionDelay:250}).refresh()},w=document.getElementById("search-form"),l=document.querySelector(".gallery"),i=document.querySelector(".load-more-btn"),h=document.querySelector(".loader");let u="",c=1;const f=15;let y;T();w.addEventListener("submit",D);i.addEventListener("click",N);function S(e){if(h.style.display="none",(e.totalHits===0||e.hits&&e.hits.length===0)&&l.innerHTML.trim()==="")_();else{const s=Math.ceil(e.totalHits/f),n=l.querySelectorAll(".gallery-item").length;c>=s?(p(e.hits),y=new g(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),i.classList.add("is-hidden"),m()):n>=e.totalHits?(i.classList.add("is-hidden"),m()):(p(e.hits),y=new g(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),i.classList.remove("is-hidden"),M(E()*2))}}function D(e){if(e.preventDefault(),c=1,u=e.currentTarget.searchQuery.value.trim(),l.innerHTML="",i.classList.add("is-hidden"),u===""){O();return}const r=e.currentTarget.searchQuery;r&&(r.value=""),L(u,c,f).then(({data:s})=>{S(s)}).catch(s=>console.log(s))}function E(){const e=document.querySelector(".gallery-item");return e?e.getBoundingClientRect().height:0}function M(e){window.scrollBy({top:e,behavior:"smooth"})}function T(){l.innerHTML=""}function N(){h.style.display="block",c+=1,y.destroy(),L(u,c,f).then(({data:e})=>{l.querySelectorAll(".gallery-item").length>=e.totalHits?(i.classList.add("is-hidden"),m()):S(e)}).catch(e=>console.log(e)).finally(()=>{h.style.display="none"})}function O(){d.error({title:"Error",message:"The search string cannot be empty. Please specify your search query."})}function m(){d.error({title:"",message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})}function _(){d.error({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"})}
//# sourceMappingURL=commonHelpers.js.map
